services:
  web:
    # image: gcm3:latest
    build: .
    # command: ["sh", "./bin/migrate"]
    ports:
     - 4000:4000
    environment:
      DATABASE_URL: "ecto://postgres:postgres@db:5432/gcm3_survey"
      SECRET_KEY_BASE: "7ZLE7f8ByXX7p+YlHGvrlkmqixIETWhYNxEFUfl7XT5mdIOeYuD/24xkKg1iGDvJ"
      PHX_HOST: "localhost"
    depends_on:
      - db
  
  db:
    image: postgres:alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gcm3_survey